[config]
managed_dir = "/home/nloken/.config"
excluded_dirs = [".git", ".jj", "node_modules"]

[[entries]]
name = "ags"
source = "/home/nloken/dotfiles/ags"
root = "/home/nloken/.config/ags"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/tsconfig.json"
link = "/home/nloken/.config/ags/tsconfig.json"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/node_modules"
link = "/home/nloken/.config/ags/node_modules"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/env.d.ts"
link = "/home/nloken/.config/ags/env.d.ts"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/@girs"
link = "/home/nloken/.config/ags/@girs"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/main.tsx"
link = "/home/nloken/.config/ags/main.tsx"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ags/style.scss"
link = "/home/nloken/.config/ags/style.scss"
linkstate = "Linked"

[[entries]]
name = "dunst"
source = "/home/nloken/dotfiles/dunst"
root = "/home/nloken/.config/dunst"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/dunst/dunstrc"
link = "/home/nloken/.config/dunst/dunstrc"
linkstate = "Linked"

[[entries]]
name = "fish"
source = "/home/nloken/dotfiles/fish"
root = "/home/nloken/.config/fish"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/completions"
link = "/home/nloken/.config/fish/completions"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/conf.d"
link = "/home/nloken/.config/fish/conf.d"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/fish_plugins"
link = "/home/nloken/.config/fish/fish_plugins"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/functions"
link = "/home/nloken/.config/fish/functions"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/themes"
link = "/home/nloken/.config/fish/themes"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/config.fish"
link = "/home/nloken/.config/fish/config.fish"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/fish/fish_variables"
link = "/home/nloken/.config/fish/fish_variables"
linkstate = "Linked"

[[entries]]
name = "ghostty"
source = "/home/nloken/dotfiles/ghostty"
root = "/home/nloken/.config/ghostty"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ghostty/themes"
link = "/home/nloken/.config/ghostty/themes"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/ghostty/config"
link = "/home/nloken/.config/ghostty/config"
linkstate = "Linked"

[[entries]]
name = "git"
source = "/home/nloken/dotfiles/git"
root = "/home/nloken/.config/git"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/git/config"
link = "/home/nloken/.config/git/config"
linkstate = "Linked"

[[entries]]
name = "hypr"
source = "/home/nloken/dotfiles/hypr"
root = "/home/nloken/.config/hypr"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/hyprpaper.conf"
link = "/home/nloken/.config/hypr/hyprpaper.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/env.conf"
link = "/home/nloken/.config/hypr/env.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/mocha.conf"
link = "/home/nloken/.config/hypr/mocha.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/gruvbox.conf"
link = "/home/nloken/.config/hypr/gruvbox.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/hyprlock.conf"
link = "/home/nloken/.config/hypr/hyprlock.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/power-state-workaround.sh"
link = "/home/nloken/.config/hypr/power-state-workaround.sh"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/hypridle.conf"
link = "/home/nloken/.config/hypr/hypridle.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/hypr/hyprland.conf"
link = "/home/nloken/.config/hypr/hyprland.conf"
linkstate = "Linked"

[[entries]]
name = "kitty"
source = "/home/nloken/dotfiles/kitty"
root = "/home/nloken/.config/kitty"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/kitty/current-theme.conf"
link = "/home/nloken/.config/kitty/current-theme.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/kitty/kitty.conf"
link = "/home/nloken/.config/kitty/kitty.conf"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/kitty/kitty.conf.bak"
link = "/home/nloken/.config/kitty/kitty.conf.bak"
linkstate = "Linked"

[[entries]]
name = "nvim"
source = "/home/nloken/dotfiles/nvim"
root = "/home/nloken/.config/nvim"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/nvim/_after"
link = "/home/nloken/.config/nvim/_after"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/nvim/init.lua"
link = "/home/nloken/.config/nvim/init.lua"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/nvim/lua"
link = "/home/nloken/.config/nvim/lua"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/nvim/stylua.toml"
link = "/home/nloken/.config/nvim/stylua.toml"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/nvim/lazy-lock.json"
link = "/home/nloken/.config/nvim/lazy-lock.json"
linkstate = "Linked"

[[entries]]
name = "tmux"
source = "/home/nloken/dotfiles/tmux"
root = "/home/nloken/.config/tmux"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/tmux/tmux.conf"
link = "/home/nloken/.config/tmux/tmux.conf"
linkstate = "Linked"

[[entries]]
name = "zathura"
source = "/home/nloken/dotfiles/zathura"
root = "/home/nloken/.config/zathura"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/zathura/zathurarc"
link = "/home/nloken/.config/zathura/zathurarc"
linkstate = "Linked"

[[entries.tracked_files]]
source = "/home/nloken/dotfiles/zathura/catppuccin-mocha"
link = "/home/nloken/.config/zathura/catppuccin-mocha"
linkstate = "Linked"
