general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = sh -c 'pidof hyprlock >/dev/null && ~/.config/hypr/power-state-workaround.sh suspend'
}
